version: 2.1
jobs:

  test:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: ./build.sh decrypt
      #- run: ./build.sh docker_build
      #- run: ./build.sh docker_serviceaccount
      #- run: ./build.sh docker_test dsopzproj "dsopz-it-$(($RANDOM % 100))-"
      #- run: ./build.sh docker_package
      - run: mkdir - dist; echo x > dist/README
      - run: ./build.sh docker_gh_release edge

  deploy_pip:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: [[ "$CIRCLE_TAG" != "x" ]]
      - run: ./build.sh docker_gh_release "$CIRCLE_TAG"

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^dsopz\-.*/
      
      - deploy_pip:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^dsopz\-.*/

          