version: 2.1
jobs:

  test:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: ./build.sh decrypt
      #- run: ./build.sh cmd_docker_build
      #- run: ./build.sh docker_serviceaccount
      #- run: ./build.sh docker_test dsopzproj

  deploy_pip:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: echo b

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^dsopz\-.*/
      
      - deploy_pip:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^dsopz\-.*/

          