version: 2.1
jobs:

  test:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: ./build.sh decrypt
      - run: ./build.sh docker_build_python
      - run: ./build.sh docker_build_go
      - run: ./build.sh docker_serviceaccount
      - run: ./build.sh docker_test dsopzproj "dsopz-it-$(($RANDOM % 100))-"
      - run: ./build.sh docker_package
      - persist_to_workspace:
          root: dist
          paths: 
            - ./*


  gh-release-master:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: du -hs dist/*
      - run: ./build.sh docker_build_go
      - run: ./build.sh docker_gh_release edge

  gh-release-tag:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - attach_workspace:
          at: target/wp-iso
      - run: du -hs dist/*
      - run: ./build.sh docker_build_go
      - run: ./build.sh docker_gh_release "$CIRCLE_TAG"

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^.*/

      - gh-release-master:
          requires:
            - test
          filters:
            branches:
              only: /^master$/

      - gh-release-tag:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^dsopz\-.*/

          